'use client';

import { upload } from '@vercel/blob/client';
import { Camera, CheckCircle2, LoaderCircle, RefreshCw, Smartphone, UploadCloud } from 'lucide-react';
import { useSearchParams } from 'next/navigation';
import { Suspense, useCallback, useEffect, useRef, useState } from 'react';
import { FaceLandmarker, FilesetResolver, HandLandmarker, PoseLandmarker } from '@mediapipe/tasks-vision';
import { getPendingUpload, PendingUpload, removePendingUpload, savePendingUpload } from '@/lib/pending-upload';
import { CameraStatus, CameraView, captureStem, isSessionSnapshot, SessionConfig, VIEWS } from '@/lib/session';
import { errorMessage, readJsonSafely } from '@/lib/http';

type AppState='setup'|'loading'|'ready'|'countdown'|'recording'|'uploading'|'complete'|'error';
type Frame={timestamp:number;elapsedMs:number;hands:unknown;pose:unknown;face:unknown};
const labels:Record<CameraView,string>={front:'Front',left:'Left',right:'Right'};
const mimeType=()=>['video/mp4;codecs=h264','video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find((type)=>MediaRecorder.isTypeSupported(type))||'';

function CameraContent(){
  const params=useSearchParams();const sessionId=params.get('session')||'';const phoneToken=params.get('token')||'';
  const videoRef=useRef<HTMLVideoElement>(null);const streamRef=useRef<MediaStream|null>(null);const recorderRef=useRef<MediaRecorder|null>(null);const chunksRef=useRef<Blob[]>([]);const framesRef=useRef<Frame[]>([]);const modelsRef=useRef<{hands:HandLandmarker;pose:PoseLandmarker;face:FaceLandmarker}|null>(null);const configRef=useRef<SessionConfig|null>(null);const handledRef=useRef('');const deviceRef=useRef('');const offsetRef=useRef(0);
  const [view,setView]=useState<CameraView|''>('');const [facing,setFacing]=useState<'user'|'environment'>('user');const [state,setState]=useState<AppState>('setup');const [message,setMessage]=useState('Choose this phone’s position.');const [countdown,setCountdown]=useState<number|null>(null);const [frameCount,setFrameCount]=useState(0);const [preview,setPreview]=useState(false);const [pendingKey,setPendingKey]=useState('');
  const apiUrl=useCallback(()=>`/api/session/${encodeURIComponent(sessionId)}?role=phone&token=${encodeURIComponent(phoneToken)}`,[phoneToken,sessionId]);
  useEffect(()=>{deviceRef.current=sessionStorage.getItem('bsl-device')||crypto.randomUUID();sessionStorage.setItem('bsl-device',deviceRef.current);return()=>streamRef.current?.getTracks().forEach((track)=>track.stop());},[]);
  const status=useCallback(async(next:CameraStatus['state'],ready:boolean,extra:Partial<CameraStatus>={})=>{if(!view)return;const response=await fetch(apiUrl(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'status',status:{view,deviceId:deviceRef.current,state:next,ready,...extra}})});if(!response.ok){const value=await readJsonSafely(response);throw new Error(errorMessage(value,`Could not update phone status (HTTP ${response.status}).`));}},[apiUrl,view]);
  const createModels=async(delegate:'GPU'|'CPU')=>{const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/wasm');const base=(modelAssetPath:string)=>({modelAssetPath,delegate});const [hands,pose,face]=await Promise.all([HandLandmarker.createFromOptions(vision,{baseOptions:base('https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task'),runningMode:'VIDEO',numHands:2}),PoseLandmarker.createFromOptions(vision,{baseOptions:base('https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task'),runningMode:'VIDEO',numPoses:1}),FaceLandmarker.createFromOptions(vision,{baseOptions:base('https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task'),runningMode:'VIDEO',numFaces:1})]);return{hands,pose,face};};
  const prepare=async()=>{if(!view)return;setState('loading');setMessage('Opening camera and loading MediaPipe…');try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:facing,width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}},audio:false});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play();setPreview(true);}if(!modelsRef.current){try{modelsRef.current=await createModels('GPU');}catch{modelsRef.current=await createModels('CPU');}}await status('ready',true);setState('ready');setMessage(`${labels[view]} view ready. Keep this page open.`);}catch(cause){setState('error');setMessage(cause instanceof Error?cause.message:'Camera setup failed.');}};
  useEffect(()=>{if(state!=='recording')return;let active=true;const started=performance.now();const loop=()=>{if(!active)return;const video=videoRef.current;const models=modelsRef.current;if(video&&models&&video.readyState>=2){const now=performance.now();try{const hands=models.hands.detectForVideo(video,now);const pose=models.pose.detectForVideo(video,now);const face=models.face.detectForVideo(video,now);framesRef.current.push({timestamp:Date.now(),elapsedMs:now-started,hands:hands.landmarks,pose:pose.landmarks,face:face.faceLandmarks});if(framesRef.current.length%10===0)setFrameCount(framesRef.current.length);}catch{/* preserve video when one inference frame fails */}}requestAnimationFrame(loop);};requestAnimationFrame(loop);return()=>{active=false;};},[state]);
  const begin=useCallback((startAt:number)=>{if(!streamRef.current||recorderRef.current?.state==='recording')return;const targetLocal=startAt-offsetRef.current;const delay=Math.max(0,targetLocal-Date.now());if(Date.now()-targetLocal>1500){setState('error');setMessage('The start signal arrived too late. Reset this take from the controller.');void status('error',false,{error:'Stale start command'});return;}setState('countdown');const tick=window.setInterval(()=>setCountdown(Math.max(1,Math.ceil((targetLocal-Date.now())/1000))),150);window.setTimeout(()=>{clearInterval(tick);setCountdown(null);chunksRef.current=[];framesRef.current=[];setFrameCount(0);const selected=mimeType();const recorder=new MediaRecorder(streamRef.current!,selected?{mimeType:selected,videoBitsPerSecond:5_000_000}:undefined);recorder.ondataavailable=(event)=>{if(event.data.size)chunksRef.current.push(event.data);};recorder.onerror=()=>{setState('error');setMessage('The browser stopped the recording unexpectedly.');};recorderRef.current=recorder;recorder.start(1000);setState('recording');setMessage('Recording…');void status('recording',true);},delay);},[status]);
  const uploadPending=useCallback(async(item:PendingUpload)=>{setState('uploading');setMessage('Uploading directly to private storage…');const payload=JSON.stringify({sessionId:item.sessionId,phoneToken:item.phoneToken,view:item.view});const extension=item.video.type.includes('mp4')?'mp4':'webm';const video=await upload(`${item.pathnameBase}.${extension}`,item.video,{access:'private',handleUploadUrl:'/api/blob/upload',clientPayload:payload,multipart:true});const landmarks=await upload(`${item.pathnameBase}_landmarks.json`,item.landmarks,{access:'private',handleUploadUrl:'/api/blob/upload',clientPayload:payload,multipart:true});await status('complete',false,{filename:`${item.pathnameBase.split('/').at(-1)}.${extension}`,videoUrl:video.url,landmarksUrl:landmarks.url});await removePendingUpload(item.key);setPendingKey('');setState('complete');setMessage('Video and landmarks uploaded successfully.');},[status]);
  const stop=useCallback(async()=>{const recorder=recorderRef.current;const config=configRef.current;if(!recorder||recorder.state==='inactive'||!config||!view)return;setState('uploading');await status('uploading',false);await new Promise<void>((resolve)=>{recorder.onstop=()=>resolve();recorder.stop();});const type=recorder.mimeType||'video/webm';const video=new Blob(chunksRef.current,{type});const metadata={schemaVersion:1,session:config,view,deviceId:deviceRef.current,frameCount:framesRef.current.length,frames:framesRef.current};const stem=captureStem(config,view);const key=`${sessionId}:${view}:${config.takeId}`;const item:PendingUpload={key,video,landmarks:new Blob([JSON.stringify(metadata)],{type:'application/json'}),pathnameBase:`captures/${config.participant}/${config.sessionLabel}/${config.sign}/${config.take}/${stem}`,sessionId,phoneToken,view};await savePendingUpload(item);setPendingKey(key);try{await uploadPending(item);}catch(cause){setState('error');setMessage(`${cause instanceof Error?cause.message:'Upload failed.'} The recording is saved on this phone; tap Retry upload.`);}},[phoneToken,sessionId,status,uploadPending,view]);
  useEffect(()=>{if(!view||!['ready','countdown','recording','complete'].includes(state))return;const poll=async()=>{const sent=Date.now();try{const response=await fetch(apiUrl(),{cache:'no-store'});const received=Date.now();const value:unknown=await response.json();if(!response.ok||!isSessionSnapshot(value))return;offsetRef.current=value.serverTime-(sent+received)/2;configRef.current=value.config;const command=value.command;if(command.takeId!==value.config.takeId||command.id===handledRef.current)return;handledRef.current=command.id;if(command.type==='start'&&state==='ready'&&command.startAt)begin(command.startAt);if(command.type==='stop'&&state==='recording')void stop();if(state==='ready')await status('ready',true);}catch{/* retry on next poll */}};void poll();const timer=window.setInterval(()=>void poll(),600);return()=>clearInterval(timer);},[apiUrl,begin,state,status,stop,view]);
  const retry=async()=>{const item=await getPendingUpload(pendingKey);if(item)try{await uploadPending(item);}catch(cause){setMessage(cause instanceof Error?cause.message:'Retry failed.');}};
  return <main className="mx-auto flex min-h-screen max-w-2xl flex-col px-4 py-5"><header className="flex items-center justify-between border-b border-white/10 pb-4"><div className="flex items-center gap-3"><Camera className="text-cyan-300"/><div><p className="font-semibold">Multi-View BSL phone</p><p className="text-xs text-slate-500">Secure capture session</p></div></div><span className="status-chip"><span className={state==='recording'?'h-2 w-2 animate-pulse rounded-full bg-rose-400':'status-dot'}/>{state}</span></header><section className="flex flex-1 flex-col pt-5"><div className="camera-card relative aspect-[3/4] sm:aspect-video" data-facing={facing}><video ref={videoRef} playsInline muted className={preview?'':'opacity-30'}/>{!preview&&<div className="absolute inset-0 grid place-items-center text-slate-500"><Smartphone size={42}/></div>}{countdown&&<div className="absolute inset-0 grid place-items-center bg-slate-950/60 text-8xl font-bold text-cyan-300">{countdown}</div>}</div><div className="panel mt-4 p-5"><p className="text-sm leading-6 text-slate-300">{message}</p>{state==='recording'&&<p className="mt-2 text-xs text-slate-500">MediaPipe frames: {frameCount}</p>}{state==='setup'&&<><div className="mt-5 grid grid-cols-3 gap-2">{VIEWS.map((item)=><button key={item} onClick={()=>setView(item)} className={`secondary-button ${view===item?'!border-cyan-300 !text-cyan-200':''}`}>{labels[item]}</button>)}</div><label className="mt-4">Physical camera<select value={facing} onChange={(event)=>setFacing(event.target.value as typeof facing)}><option value="user">Front / selfie</option><option value="environment">Back camera</option></select></label><button className="primary-button mt-5 w-full" disabled={!view||!sessionId||!phoneToken} onClick={()=>void prepare()}><Camera size={18}/>Open camera & become ready</button></>}{state==='loading'&&<p className="mt-5 flex justify-center gap-2 text-cyan-200"><LoaderCircle className="animate-spin"/>Loading models…</p>}{state==='ready'&&<p className="mt-5 flex justify-center gap-2 text-emerald-300"><CheckCircle2/>Ready — waiting for controller</p>}{state==='uploading'&&<p className="mt-5 flex justify-center gap-2 text-cyan-200"><UploadCloud/>Uploading…</p>}{state==='error'&&pendingKey&&<button className="primary-button mt-5 w-full" onClick={()=>void retry()}><RefreshCw size={17}/>Retry upload</button>}</div></section></main>;
}

export default function CameraPage(){return <Suspense fallback={<main className="grid min-h-screen place-items-center text-slate-400">Opening secure camera session…</main>}><CameraContent/></Suspense>;}
