'use client';

import { ArrowLeft, Check, CircleStop, Clock3, Copy, Play, QrCode, Smartphone } from 'lucide-react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { Suspense, useCallback, useEffect, useMemo, useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { CameraView, isSessionSnapshot, SessionSnapshot, VIEWS } from '@/lib/session';
import { errorMessage, readJsonSafely } from '@/lib/http';

const labels: Record<CameraView,string>={front:'Front view',left:'Left view',right:'Right view'};
function ControllerContent(){
  const params=useSearchParams(); const sessionId=params.get('session')||''; const controllerToken=params.get('controllerToken')||''; const phoneToken=params.get('phoneToken')||'';
  const [snapshot,setSnapshot]=useState<SessionSnapshot|null>(null); const [origin,setOrigin]=useState(''); const [notice,setNotice]=useState('Waiting for three phones…'); const [now,setNow]=useState(0);
  const authUrl=useMemo(()=>`/api/session/${encodeURIComponent(sessionId)}?role=controller&token=${encodeURIComponent(controllerToken)}`,[controllerToken,sessionId]);
  const fetchSnapshot=useCallback(async()=>{if(!sessionId||!controllerToken)return; const response=await fetch(authUrl,{cache:'no-store'}); const value=await readJsonSafely(response); if(response.ok&&isSessionSnapshot(value)){setSnapshot(value);setNow(Date.now());}else if(!response.ok)setNotice(errorMessage(value,`Session request failed (HTTP ${response.status}).`));},[authUrl,controllerToken,sessionId]);
  useEffect(()=>{const start=window.setTimeout(()=>{setOrigin(window.location.origin);void fetchSnapshot();},0);const timer=window.setInterval(()=>void fetchSnapshot(),1000);return()=>{clearTimeout(start);clearInterval(timer);};},[fetchSnapshot]);
  const issue=useCallback(async(action:'start'|'stop')=>{setNotice(action==='start'?'Starting all cameras in five seconds…':'Stopping and uploading…');const response=await fetch(authUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const value=await readJsonSafely(response);if(!response.ok)setNotice(errorMessage(value,`Command failed (HTTP ${response.status}).`));await fetchSnapshot();},[authUrl,fetchSnapshot]);
  const rawCameras=snapshot?.cameras??{};
  const secureDownload=(filePath:string)=>`/api/file?session=${encodeURIComponent(sessionId)}&token=${encodeURIComponent(controllerToken)}&path=${encodeURIComponent(filePath)}`;
  const cameras=Object.fromEntries(VIEWS.map((cameraView)=>{const camera=rawCameras[cameraView];return[cameraView,camera?{...camera,videoUrl:camera.videoUrl?secureDownload(camera.videoUrl):undefined,landmarksUrl:camera.landmarksUrl?secureDownload(camera.landmarksUrl):undefined}:undefined];})) as typeof rawCameras;
  const allReady=VIEWS.every((view)=>cameras[view]?.ready&&now-(cameras[view]?.updatedAt??0)<15000);const recording=snapshot?.command.type==='start';
  const phoneUrl=origin&&`${origin}/camera?session=${encodeURIComponent(sessionId)}&token=${encodeURIComponent(phoneToken)}`;
  return <main className="min-h-screen px-4 py-5 sm:px-8"><header className="mx-auto flex max-w-7xl items-center justify-between border-b border-white/10 pb-5"><Link href="/" className="flex items-center gap-2 text-sm text-slate-300"><ArrowLeft size={17}/>New session</Link><div className="text-right"><p className="font-semibold">{snapshot?.config.participant??'Session'}</p><p className="text-xs text-slate-400">{snapshot?.config.sign} · {snapshot?.config.take}</p></div></header>
  <section className="mx-auto grid max-w-7xl gap-6 pt-7 lg:grid-cols-[340px_1fr]"><aside className="panel p-5"><div className="flex items-center gap-2"><QrCode size={19} className="text-cyan-300"/><p className="eyebrow">Connect phones</p></div><h1 className="mt-3 text-2xl font-semibold">One code. Three cameras.</h1><p className="mt-2 text-sm leading-6 text-slate-400">Scan on each phone and assign a unique view.</p><div className="mx-auto my-6 grid aspect-square w-full max-w-[250px] place-items-center rounded-2xl bg-white p-4">{phoneUrl&&<QRCodeSVG value={phoneUrl} size={218} level="M" marginSize={0}/>}</div><button className="secondary-button w-full" onClick={()=>void navigator.clipboard.writeText(phoneUrl)}><Copy size={16}/>Copy phone link</button></aside>
  <div className="space-y-6"><div className="panel p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Live readiness</p><h2 className="mt-2 text-2xl font-semibold">Camera positions</h2></div><span className="status-chip">{VIEWS.filter((v)=>cameras[v]?.ready).length}/3 ready</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{VIEWS.map((view)=>{const camera=cameras[view];const online=Boolean(camera&&now-camera.updatedAt<15000);return <article key={view} className="camera-card p-4"><div className="flex items-center justify-between"><Smartphone className={online?'text-cyan-300':'text-slate-600'}/>{camera?.ready&&online?<Check className="text-emerald-300"/>:<Clock3 className="text-slate-600"/>}</div><h3 className="mt-8 font-semibold">{labels[view]}</h3><p className="mt-1 text-xs capitalize text-slate-500">{online?camera?.state:'Waiting for phone'}</p>{camera?.videoUrl&&<div className="mt-3 flex gap-3 text-xs"><a className="text-cyan-300" href={camera.videoUrl}>Video</a><a className="text-cyan-300" href={camera.landmarksUrl}>Landmarks</a></div>}</article>;})}</div></div>
  <div className="panel flex flex-col gap-5 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">Capture controls</p><p className="mt-2 text-sm text-slate-300">{notice}</p></div>{!recording?<button className="primary-button" onClick={()=>void issue('start')} disabled={!allReady}><Play size={17}/>Start all</button>:<button className="danger-button" onClick={()=>void issue('stop')}><CircleStop size={18}/>Stop & upload</button>}</div></div></section></main>;
}

export default function ControllerPage(){return <Suspense fallback={<main className="grid min-h-screen place-items-center text-slate-400">Opening control room…</main>}><ControllerContent/></Suspense>;}
