'use client';

import { ArrowLeft, Check, ChevronLeft, ChevronRight, CircleStop, Clock3, Copy, FolderTree, Play, QrCode, Smartphone, Tags } from 'lucide-react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { Suspense, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { CameraView, isSessionSnapshot, SessionSnapshot, VIEWS } from '@/lib/session';
import { errorMessage, readJsonSafely } from '@/lib/http';

const labels: Record<CameraView,string>={front:'Front view',left:'Left view',right:'Right view'};
function ControllerContent(){
  const params=useSearchParams(); const sessionId=params.get('session')||''; const controllerToken=params.get('controllerToken')||''; const phoneToken=params.get('phoneToken')||'';
  const [snapshot,setSnapshot]=useState<SessionSnapshot|null>(null); const [origin,setOrigin]=useState(''); const [notice,setNotice]=useState('Waiting for three phones…'); const [now,setNow]=useState(0); const [sign,setSign]=useState(''); const [take,setTake]=useState(''); const [durationSeconds,setDurationSeconds]=useState(5); const [preparing,setPreparing]=useState(false); const [categories,setCategories]=useState<Record<string,string[]>>({}); const [category,setCategory]=useState(''); const [nameIndex,setNameIndex]=useState(0); const namingInitialized=useRef(false);
  const authUrl=useMemo(()=>`/api/session/${encodeURIComponent(sessionId)}?role=controller&token=${encodeURIComponent(controllerToken)}`,[controllerToken,sessionId]);
  const fetchSnapshot=useCallback(async()=>{if(!sessionId||!controllerToken)return; try{const response=await fetch(authUrl,{cache:'no-store'}); const value=await readJsonSafely(response); if(response.ok&&isSessionSnapshot(value)){setSnapshot(value);setNow(value.serverTime);if(!namingInitialized.current){namingInitialized.current=true;setSign(value.config.sign);setTake(value.config.take);}}else if(!response.ok)setNotice(errorMessage(value,`Session request failed (HTTP ${response.status}).`));}catch{setNotice('Connection interrupted. Retrying automatically…');}},[authUrl,controllerToken,sessionId]);
  useEffect(()=>{const start=window.setTimeout(()=>{setOrigin(window.location.origin);void fetchSnapshot();},0);const timer=window.setInterval(()=>void fetchSnapshot(),1000);return()=>{clearTimeout(start);clearInterval(timer);};},[fetchSnapshot]);
  useEffect(()=>{if(!sessionId||!controllerToken)return;const load=async()=>{try{const response=await fetch(`/api/collection-names?session=${encodeURIComponent(sessionId)}&token=${encodeURIComponent(controllerToken)}`,{cache:'no-store'});const value=await readJsonSafely(response);if(!response.ok||!value||typeof value!=='object')return;const loaded=(value as{categories?:Record<string,string[]>}).categories;if(!loaded)return;setCategories(loaded);const first=Object.keys(loaded).sort()[0]||'';setCategory(first);if(first&&loaded[first]?.length){setNameIndex(0);setSign(loaded[first][0]);}}catch{/* manual naming remains available */}};void load();},[controllerToken,sessionId]);
  const issue=useCallback(async(action:'start'|'stop')=>{setNotice(action==='start'?`Starting in five seconds, then recording for ${durationSeconds} seconds…`:'Stopping early and uploading…');try{const response=await fetch(authUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,durationSeconds})});const value=await readJsonSafely(response);if(!response.ok)setNotice(errorMessage(value,`Command failed (HTTP ${response.status}).`));await fetchSnapshot();}catch{setNotice('Could not reach the laptop. Check the tunnel and try again.');}},[authUrl,durationSeconds,fetchSnapshot]);
  const prepare=useCallback(async()=>{if(!sign.trim()||!take.trim())return;setPreparing(true);setNotice('Preparing the connected phones for the named recording…');try{const response=await fetch(authUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'prepare',category:category||'uncategorized',sign,take})});const value=await readJsonSafely(response);if(!response.ok){setNotice(errorMessage(value,`Could not prepare recording (HTTP ${response.status}).`));return;}setNotice(`Prepared ${sign} · ${take}. Waiting for all phones to confirm…`);await fetchSnapshot();}catch{setNotice('Could not prepare the recording. Check the tunnel and try again.');}finally{setPreparing(false);}},[authUrl,category,fetchSnapshot,sign,take]);
  const rawCameras=snapshot?.cameras??{};
  const secureDownload=(filePath:string)=>`/api/file?session=${encodeURIComponent(sessionId)}&token=${encodeURIComponent(controllerToken)}&path=${encodeURIComponent(filePath)}`;
  const cameras=Object.fromEntries(VIEWS.map((cameraView)=>{const camera=rawCameras[cameraView];return[cameraView,camera?{...camera,videoUrl:camera.videoUrl?secureDownload(camera.videoUrl):undefined,landmarksUrl:camera.landmarksUrl?secureDownload(camera.landmarksUrl):undefined}:undefined];})) as typeof rawCameras;
  const allReady=VIEWS.every((view)=>cameras[view]?.ready&&now-(cameras[view]?.updatedAt??0)<15000);const recording=snapshot?.command.type==='start';const canStart=allReady&&snapshot?.command.type==='idle';
  const phoneUrl=origin&&`${origin}/camera?session=${encodeURIComponent(sessionId)}&token=${encodeURIComponent(phoneToken)}`;
  const names=categories[category]??[];
  const chooseCategory=(nextCategory:string)=>{setCategory(nextCategory);setNameIndex(0);if(categories[nextCategory]?.length)setSign(categories[nextCategory][0]);};
  const moveName=(direction:-1|1)=>{if(!names.length)return;const next=(nameIndex+direction+names.length)%names.length;setNameIndex(next);setSign(names[next]);};
  return <main className="min-h-screen px-4 py-5 sm:px-8"><header className="mx-auto flex max-w-7xl items-center justify-between border-b border-white/10 pb-5"><Link href="/" className="flex items-center gap-2 text-sm text-slate-300"><ArrowLeft size={17}/>New collection</Link><div className="text-right"><p className="font-semibold capitalize">{snapshot?.config.category??'Collection'}</p><p className="text-xs text-slate-400">{snapshot?.config.sign} · {snapshot?.config.take}</p></div></header>
  <section className="mx-auto grid max-w-7xl gap-6 pt-7 lg:grid-cols-[340px_1fr]"><aside className="panel p-5"><div className="flex items-center gap-2"><QrCode size={19} className="text-cyan-300"/><p className="eyebrow">Connect phones</p></div><h1 className="mt-3 text-2xl font-semibold">One code. Three cameras.</h1><p className="mt-2 text-sm leading-6 text-slate-400">Scan on each phone and assign a unique view.</p><div className="mx-auto my-6 grid aspect-square w-full max-w-[250px] place-items-center rounded-2xl bg-white p-4">{phoneUrl&&<QRCodeSVG value={phoneUrl} size={218} level="M" marginSize={0}/>}</div><button className="secondary-button w-full" onClick={()=>void navigator.clipboard.writeText(phoneUrl)}><Copy size={16}/>Copy phone link</button></aside>
  <div className="space-y-6"><div className="panel p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Live readiness</p><h2 className="mt-2 text-2xl font-semibold">Camera positions</h2></div><span className="status-chip">{VIEWS.filter((v)=>cameras[v]?.ready&&now-(cameras[v]?.updatedAt??0)<15000).length}/3 ready</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{VIEWS.map((view)=>{const camera=cameras[view];const online=Boolean(camera&&now-camera.updatedAt<15000);return <article key={view} className="camera-card p-4"><div className="flex items-center justify-between"><Smartphone className={online?'text-cyan-300':'text-slate-600'}/>{camera?.ready&&online?<Check className="text-emerald-300"/>:<Clock3 className="text-slate-600"/>}</div><h3 className="mt-8 font-semibold">{labels[view]}</h3><p className="mt-1 text-xs capitalize text-slate-500">{online?camera?.state:'Waiting for phone'}</p>{camera?.videoUrl&&<div className="mt-3 flex gap-3 text-xs"><a className="text-cyan-300" href={camera.videoUrl}>Video</a><a className="text-cyan-300" href={camera.landmarksUrl}>Landmarks</a></div>}</article>;})}</div></div>
  <div className="panel p-5 sm:p-6"><div className="flex items-center gap-2"><Tags size={18} className="text-cyan-300"/><p className="eyebrow">Recording name</p></div><p className="mt-2 text-sm text-slate-400">Choose a folder name or type your own. The connected phones stay paired—no new QR scan.</p>{Object.keys(categories).length>0&&<div className="mt-4 rounded-xl border border-white/10 bg-slate-950/30 p-4"><div className="flex items-center gap-2 text-sm text-slate-300"><FolderTree size={17} className="text-cyan-300"/>Folder queue</div><div className="mt-3 grid gap-3 sm:grid-cols-[1fr_auto]"><label>Category<select value={category} onChange={(event)=>chooseCategory(event.target.value)} disabled={recording}>{Object.keys(categories).sort().map((item)=><option value={item} key={item}>{item}</option>)}</select></label><div className="flex items-end gap-2"><button className="secondary-button" aria-label="Previous name" onClick={()=>moveName(-1)} disabled={recording||names.length<2}><ChevronLeft size={17}/></button><span className="min-w-24 pb-3 text-center text-xs text-slate-400">{names.length?`${nameIndex+1} / ${names.length}`:'0 / 0'}</span><button className="secondary-button" aria-label="Next name" onClick={()=>moveName(1)} disabled={recording||names.length<2}><ChevronRight size={17}/></button></div></div></div>}<div className="mt-4 grid gap-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><label>Sign / gloss<input value={sign} onChange={(event)=>setSign(event.target.value)} required disabled={recording}/></label><label>Take<input value={take} onChange={(event)=>setTake(event.target.value)} required disabled={recording}/></label><button className="secondary-button" onClick={()=>void prepare()} disabled={recording||preparing||!sign.trim()||!take.trim()}>{preparing?'Preparing…':'Prepare recording'}</button></div></div>
  <div className="panel flex flex-col gap-5 p-5 sm:flex-row sm:items-end sm:justify-between"><div className="flex-1"><p className="eyebrow">Capture controls</p><p className="mt-2 text-sm text-slate-300">{notice}</p></div><label className="w-full sm:w-36">Duration (seconds)<input type="number" min="1" max="300" step="0.5" value={durationSeconds} onChange={(event)=>setDurationSeconds(Number(event.target.value))} disabled={recording}/></label>{!recording?<button className="primary-button" onClick={()=>void issue('start')} disabled={!canStart||!Number.isFinite(durationSeconds)||durationSeconds<1||durationSeconds>300}><Play size={17}/>Start timed recording</button>:<button className="danger-button" onClick={()=>void issue('stop')}><CircleStop size={18}/>Stop early</button>}</div></div></section></main>;
}

export default function ControllerPage(){return <Suspense fallback={<main className="grid min-h-screen place-items-center text-slate-400">Opening control room…</main>}><ControllerContent/></Suspense>;}
